-- Skywolfe Mods - Supabase schema
-- Rode este arquivo inteiro no Supabase SQL Editor.
-- Ele e idempotente: pode rodar de novo sem apagar dados existentes.

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text default '' not null,
  price numeric(10, 2) default 0 not null,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

create table if not exists public.pix_config (
  id integer primary key default 1,
  key text default '' not null,
  qr_code_url text default '' not null,
  phone text default '' not null,
  updated_at timestamptz default now() not null,
  constraint pix_config_single_row check (id = 1)
);

create table if not exists public.gallery (
  id bigint generated by default as identity primary key,
  name text not null,
  image_data text not null,
  category text default 'GTA' not null,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

alter table public.gallery add column if not exists category text default 'GTA' not null;

alter table public.products add column if not exists name text;
alter table public.products alter column name set not null;
alter table public.products add column if not exists description text default '' not null;
alter table public.products add column if not exists price numeric(10, 2) default 0 not null;
alter table public.products add column if not exists created_at timestamptz default now() not null;
alter table public.products add column if not exists updated_at timestamptz default now() not null;

alter table public.pix_config add column if not exists key text default '' not null;
alter table public.pix_config add column if not exists qr_code_url text default '' not null;
alter table public.pix_config add column if not exists phone text default '' not null;
alter table public.pix_config add column if not exists updated_at timestamptz default now() not null;

create table if not exists public.comprovantes (
  id bigint generated by default as identity primary key,
  codigo_pedido text default '' not null,
  nome text not null,
  telefone text default '' not null,
  data_compra text not null,
  imagem text,
  valor numeric(10, 2) default 0 not null,
  produtos text[] default array[]::text[] not null,
  status text default 'pendente' not null,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

alter table public.comprovantes add column if not exists codigo_pedido text default '' not null;
alter table public.comprovantes add column if not exists nome text;
update public.comprovantes set nome = 'Cliente' where nome is null;
alter table public.comprovantes alter column nome set not null;
alter table public.comprovantes add column if not exists telefone text default '' not null;
alter table public.comprovantes add column if not exists data_compra text;
update public.comprovantes set data_compra = created_at::text where data_compra is null;
alter table public.comprovantes alter column data_compra set not null;
alter table public.comprovantes add column if not exists imagem text;
alter table public.comprovantes add column if not exists valor numeric(10, 2) default 0 not null;
alter table public.comprovantes add column if not exists produtos text[] default array[]::text[] not null;
alter table public.comprovantes add column if not exists status text default 'pendente' not null;
alter table public.comprovantes add column if not exists created_at timestamptz default now() not null;
alter table public.comprovantes add column if not exists updated_at timestamptz default now() not null;

create index if not exists idx_comprovantes_created_at on public.comprovantes (created_at desc);
create index if not exists idx_comprovantes_codigo_pedido on public.comprovantes (codigo_pedido);
create index if not exists idx_gallery_created_at on public.gallery (created_at desc);

alter table public.products enable row level security;
alter table public.pix_config enable row level security;
alter table public.comprovantes enable row level security;
alter table public.gallery enable row level security;

drop policy if exists "Public read products" on public.products;
drop policy if exists "Public write products" on public.products;

create policy "Public read products" on public.products
  for select using (true);

create policy "Public write products" on public.products
  for all using (true) with check (true);

drop policy if exists "Public read pix config" on public.pix_config;
drop policy if exists "Public write pix config" on public.pix_config;
drop policy if exists "Public read comprovantes" on public.comprovantes;
drop policy if exists "Public write comprovantes" on public.comprovantes;
drop policy if exists "Public read gallery" on public.gallery;
drop policy if exists "Public write gallery" on public.gallery;

create policy "Public read comprovantes" on public.comprovantes
  for select using (true);

create policy "Public write comprovantes" on public.comprovantes
  for all using (true) with check (true);

create policy "Public read gallery" on public.gallery
  for select using (true);

create policy "Public write gallery" on public.gallery
  for all using (true) with check (true);

create policy "Public read pix config" on public.pix_config
  for select using (true);

create policy "Public write pix config" on public.pix_config
  for all using (true) with check (true);

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on public.products to anon, authenticated;
grant select, insert, update, delete on public.pix_config to anon, authenticated;
grant select, insert, update, delete on public.comprovantes to anon, authenticated;
grant select, insert, update, delete on public.gallery to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;
alter default privileges in schema public grant usage, select on sequences to anon, authenticated;
alter default privileges in schema public grant select, insert, update, delete on tables to anon, authenticated;

insert into public.products (id, name, description, price) values
  (1, 'MLO', 'Criacao de interior personalizado para o seu servidor (casas, empresas, delegacias, hospitais)', 100),
  (2, 'Cenario Externo', 'Construcao de cenarios externos personalizados (ilhas, favelas, bairros, pontos de interesse)', 200),
  (3, 'Edicao de Cenario', 'Modificacao e otimizacao de cenarios ja existentes no mapa', 80),
  (4, 'Livery de Carro', 'Pintura personalizada para veiculos (viaturas, taxis, empresas, drift)', 50),
  (5, 'Edicao de Carro', 'Modificacao de handling, metas, sons e tuning de veiculos', 100),
  (6, 'Novo Emprego', 'Sistema de emprego completo com missoes, veiculos, roupas e pagamento', 250),
  (7, 'Pintura de Roupas', 'Criacao de roupas personalizadas para o servidor (uniformes, faccoes, marcas)', 60)
on conflict (id) do update set
  name = excluded.name,
  description = excluded.description,
  price = excluded.price,
  updated_at = now();

select setval(
  pg_get_serial_sequence('public.products', 'id'),
  greatest((select coalesce(max(id), 1) from public.products), 1),
  true
);

insert into public.pix_config (id, key, qr_code_url, phone)
values (1, 'skypix@gmail.com', '', '5521998808081')
on conflict (id) do update set
  key = excluded.key,
  qr_code_url = excluded.qr_code_url,
  phone = excluded.phone,
  updated_at = now();

notify pgrst, 'reload schema';
